apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-flask-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-flask-app
  template:
    metadata:
      labels:
        app: my-flask-app
    spec:
      containers:
      - name: my-flask-app
        image: ricky1101/my-flask-app:v1
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_APP
          value: main.py
        - name: FLASK_ENV
          value: development
