---
- name: Check if required packages are installed
  block:
  - name: Check package status
    command: "dpkg -s {{ item }}" # The command dpkg -s is used to check the status of a Debian package installed on the system
    loop:
    - kubelet
    - kubeadm
    - kubectl
    - docker-ce
    - splunk
    register: package_status
    ignore_errors: true

  - name: Display installed packages
    debug:
      msg: "{{ item.item }} is {{ 'installed' if item.rc == 0 else 'not installed' }}"
    loop: "{{ package_status.results }}"

  when: ansible_os_family == "Debian"

  tags:
  - check_apt_install

...