---
- name: Install Kubernetes
  block:
  - name: Add Kubernetes apt-key
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present

  - name: Add Kubernetes apt repository
    apt_repository:
      repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: kubernetes

  - name: Update apt cache
    apt:
      update_cache: yes

  - name: Install Kubernetes packages
    apt:
      name:
      - kubelet
      - kubeadm
      - kubectl
      state: present

  - name: Install pip3
    raw: sudo apt -y update &&  apt install -y python3-pip
    changed_when: false

  - name: Install kubernetes Python library
    become: true
    pip:
      name: kubernetes
      state: present

  - name: Start Docker service
    systemd:
      name: docker
      state: started
      enabled: yes

  - name: Initialize Kubernetes
    command: kubeadm init --apiserver-advertise-address={{ ansible_default_ipv4.address }} --ignore-preflight-errors=all
    args:
      creates: /etc/kubernetes/admin.conf
    register: kubeadm_init_output
    changed_when: "'kubeadm join' in kubeadm_init_output.stdout"

  - name: Install Flannel pod network add-on
    command: "kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml"
    args:
      creates: "/etc/kubernetes/manifests/kube-flannel.yaml"

  - name: Install Kubernetes Dashboard add-on
    command: "kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.2.0/aio/deploy/recommended.yaml"
    args:
      creates: "/etc/kubernetes/manifests/kubernetes-dashboard.yaml"

  - name: Check kubelet service status
    systemd:
      name: kubelet
      state: started
      enabled: yes

  tags:
  - config_k8s
  - config

...
